"""add embedding cache table

Revision ID: abc123456789
Revises: f44d02da3caf
Create Date: 2026-06-17

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'abc123456789'
down_revision: str | None = 'f44d02da3caf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fqn', sa.String(length=1024), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_index(op.f('ix_embedding_cache_fqn'), 'embedding_cache', ['fqn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_cache_fqn'), table_name='embedding_cache')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
