"""Initial schema

Revision ID: f44d02da3caf
Revises: None
Create Date: 2026-06-15 13:42:51.175241

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f44d02da3caf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_cache_key', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('file_hashes',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('hash_value', sa.String(), nullable=False),
    sa.Column('last_indexed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_table('index_states',
    sa.Column('repo_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('repo_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_states')
    op.drop_table('file_hashes')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
