"""Initial schema for Context Gateway

Revision ID: 001
Revises: None
Create Date: 2026-06-26 13:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('agent_type', sa.String(length=50), nullable=False),
        sa.Column('task_description', sa.Text(), nullable=False),
        sa.Column('intent', sa.String(length=50), nullable=False),
        sa.Column('domain', sa.String(length=100), nullable=True),
        sa.Column('risk_level', sa.String(length=20), nullable=True),
        sa.Column('files_accessed', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('nodes_accessed', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('sources_used', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('tokens_retrieved', sa.Integer(), nullable=False),
        sa.Column('tokens_delivered', sa.Integer(), nullable=False),
        sa.Column('tokens_saved', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('outcome', sa.Text(), nullable=True),
        sa.Column('files_modified', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('git_branch', sa.String(length=255), nullable=True),
        sa.Column('project_id', UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_active', 'sessions', ['status'], unique=False, postgresql_where=sa.text("status = 'in_progress'"))
    op.create_index('idx_sessions_files', 'sessions', ['files_accessed'], unique=False, postgresql_using='gin')
    op.create_index('idx_sessions_domain', 'sessions', ['domain'], unique=False)
    op.create_index('idx_sessions_agent', 'sessions', ['agent_type', 'started_at'], unique=False)
    
    op.create_table('session_events',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', UUID(as_uuid=True), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('data', JSONB(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_session', 'session_events', ['session_id', 'created_at'], unique=False)
    
    op.create_table('feedback',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', UUID(as_uuid=True), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('was_helpful', sa.Boolean(), nullable=True),
        sa.Column('missing_context', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('irrelevant_context', sa.ARRAY(sa.Text()), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint('rating BETWEEN 1 AND 5', name='check_feedback_rating'),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_feedback_session', 'feedback', ['session_id'], unique=False)
    
    op.create_table('source_health',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('source_name', sa.String(length=100), nullable=False),
        sa.Column('is_available', sa.Boolean(), nullable=False),
        sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
        sa.Column('error_rate', sa.Float(), nullable=False),
        sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_health')
    op.drop_index('idx_feedback_session', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('idx_events_session', table_name='session_events')
    op.drop_table('session_events')
    op.drop_index('idx_sessions_agent', table_name='sessions')
    op.drop_index('idx_sessions_domain', table_name='sessions')
    op.drop_index('idx_sessions_files', table_name='sessions')
    op.drop_index('idx_sessions_active', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
